name = "aihot-cataito"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-08-01"

[build]
command = "npm run build && npx @cloudflare/next-on-pages"

# CF Pages 环境变量
[vars]
BASE_URL = "https://aihot.cataito.com"